### ISSUE TITLE
Loader can't load data to a table with a counter column

### ISSUE THREAD

**Issue by KenMcK1** [brianmhess/cassandra-loader#17]
Loading a table with a counter column causes an exception saying CQL UPDATE must be used instead of INSERT. There isn't an option to make the loader do this.

    Exception in thread "main" java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:558)
        at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:599)
    Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:291)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:79)
        at com.datastax.loader.EnhancedSession.prepare(EnhancedSession.java:93)
        at com.datastax.loader.CqlDelimLoadTask.setup(CqlDelimLoadTask.java:172)
        at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:144)
        at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:69)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:102)
        at com.datastax.driver.core.SessionManager$1.apply(SessionManager.java:163)
        at com.datastax.driver.core.SessionManager$1.apply(SessionManager.java:138)
        at com.google.common.util.concurrent.Futures$1.apply(Futures.java:720)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:859)
        ... 3 more

**Comment by brianmhess** [comment]
This is a known limitation.  I will update the README.  
As an aside, CQLSH COPY also does not support loading counters.
