### ISSUE TITLE
Loader can't load data to a table with a UDT column

### ISSUE THREAD

**Issue by rs017991** [brianmhess/cassandra-loader#21]
It would be really great for the loader to support User-defined types.

Note that collections may contain UDTs and UDTs may contain collections/other UDTs, so CQLDelimParser.schemaBits(...) would need to support some level of recursion.

Side note: The skipCols options cannot be used to skip over a column with a non-supported type because parsers are eagerly built.

**Comment by brianmhess** [comment]
Skip columns would work if you quoted the UDT, or if the UDT did not have embedded delimiters.

**Comment by diegopeleteiro** [comment]
Indeed it would be great to have support to UDTs

**Comment by trex77** [comment]
The tool is great. I really loved it. Is there any solution to UDT types other than skiping the columns? My data have sets and collections and the unloader tool gives the error below:

Exception in thread "main" java.util.concurrent.ExecutionException: java.text.ParseException: Set data type not recognized (udt)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.datastax.loader.CqlDelimUnload.run(CqlDelimUnload.java:402)
        at com.datastax.loader.CqlDelimUnload.main(CqlDelimUnload.java:471)

**Comment by brianmhess** [comment]
There is a udt branch you could try.  I think that got pretty solid, but I haven't been working on this in a while.

**Comment by kalpana04-star** [comment]
This utility support UDTs?

**Comment by brianmhess** [comment]
Check out the "udt" branch.
You may also want to look at the dsbulk utility from DataStax.
