### ISSUE TITLE
loader issue: NullPointerException

### ISSUE THREAD

**Issue by nitindeokate99** [brianmhess/cassandra-loader#44]
[cqlsh 5.0.1 | Cassandra 2.2.1 | CQL spec 3.3.0 | Native protocol v4]
Use HELP for help.
cqlsh> quit

$ /disk1/imailndcas/try_out/cassandra-loader/build/cassandra-loader -f indexData.csv -host localhost -schema "mykeyspace.tbl_zz(value,id)"
Exception in thread "main" java.lang.NullPointerException
	at com.datastax.driver.core.ProtocolOptions.getProtocolVersion(ProtocolOptions.java:168)
	at com.datastax.loader.CqlDelimLoad.setup(CqlDelimLoad.java:477)
	at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:523)
	at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:616)

$cat indexData.csv
abc, 123
pqr, 345

**Comment by nitindeokate99** [comment]
nobody faced this issue before? :o:

**Comment by brianmhess** [comment]
Which version of the loader is this?  Is this from "master"?

**Comment by brianmhess** [comment]
Should also be fixed in v0.0.19
