### ISSUE TITLE
Error running cassandra-unloader

### ISSUE THREAD

**Issue by jwiencek3** [brianmhess/cassandra-loader#77]
I've downloaded version v0.0.27 of cassandra-unloader and cassandra-loader.

Attempts to execute the unloader produce this error:

cassandra-unloader -f stdout -schema "ionic_na usr_grp_dev_order" -user admin -pw xxxxxxxxxx  -host cassandra-solr-xxxxx.com
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra-solr-1a-03.node.us-southeast-1.deveng.ionic.com/10.202.9.27:9042 (com.datastax.driver.core.TransportException: [cassandra-solr-1a-03.node.us-southeast-1.deveng.ionic.com/10.202.9.27:9042] Channel has been closed))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1272)
	at com.datastax.driver.core.Cluster.init(Cluster.java:158)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:248)
	at com.datastax.loader.CqlDelimUnload.setup(CqlDelimUnload.java:329)
	at com.datastax.loader.CqlDelimUnload.run(CqlDelimUnload.java:350)
	at com.datastax.loader.CqlDelimUnload.main(CqlDelimUnload.java:444)

Can you please help me to get this running?

We are running OS:
CentOS Linux release 7.3.1611 (Core) 

C* version:

ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by brianmhess** [comment]
It appears that cassandra-unloader cannot connect to your cluster (that's the NoHostAvailableException).  Can you:
- confirm that you can connect to the same host via cqlsh (or similar), namely cassandra-solr-xxxxx.com
- try supplying a different connection point (another node in the cluster)
- try using the IP address of the node instead of the hostname
